### ISSUE TITLE
fix/memberUpdate

### ISSUE THREAD

**Issue by lala9663** [KDT3-Final-6/final-project-BE#185]
## Description

회원 수정 할 때 입력안하면 기존 데이터로 적용하게 반영
정규식 수정

## Tasks(Process)

- [x] 회원 수정 할 때 입력안하면 기존 데이터로 적용하게 반영
- [x] 휴대폰 정규식 수정
- [x] 회원 수정 할 때 정규식 반영

## References

- [link text] (link address)
