### ISSUE TITLE
feat: 주문 상세 정보 조회, 관리자용 주문 내역 목록 조회, 관리자용, 주문 상세 정보 조회 기능 구현

### ISSUE THREAD

**Issue by JeYeongR** [KDT3-Final-6/final-project-BE#22]
## Description

주문 상세 정보 조회, 관리자용 주문 내역 목록 조회, 관리자용, 주문 상세 정보 조회 기능 구현

## Tasks(Process)

- [ ] 주문 상세 정보 조회 기능 구현
- [x] 관리자용 주문 내역 목록 조회 기능 구현
- [ ] 주문 상세 정보 조회 기능 구현
