### ISSUE TITLE
feat: 카테고리를 이용한 검색 기능 구현

### ISSUE THREAD

**Issue by zoomin3022** [KDT3-Final-6/final-project-BE#24]
## Description
카테고리를 이용한 검색 기능 구현
예를 들어 쿼리 파라미터로 category=아시아 를 하면 
아시아 카테고리를 가진 모든 상품들 페이징 처리하여 보여줌

그리고 기존에 카테고리를 하나씩 전부 반환하는 거에서
(
        "그룹별 여행",
        "5070끼리",
        "지역별 여행",
        "오세아니아",
        "테마별 여행",
        "골프여행"
)

아래와 같이 변경 :(space) 단위로 파싱하면 계층적 구조로 쓸 수 있게
(
        "그룹별 여행: 5070끼리",
        "테마별 여행: 골프여행",
        "지역별 여행: 오세아니아: 하와이"
)
## Tasks(Process)

- [x] depth 3 이상 category 예시 추가 (하와이)
- [x] CATEGORY_NOT_FOUND 예외 추가
- [x] 카테고리 검색 기능 구현
