### ISSUE TITLE
feat: 상품, 기간 옵션, 카테고리 수정 구현

### ISSUE THREAD

**Issue by zoomin3022** [KDT3-Final-6/final-project-BE#28]
## Description
#8 의 PATCH /admins/products/{productId}를 구현하려다
생각보다 구현해야 할게 많아 따로 분리

GET 카테고리 list와 
GET 기간 옵션도 만들어야 한다 

## Tasks(Process)

- [x] 상품 (기간 옵션, 카테고리) 제외 수정 기능 구현
- [x] PeriodOption Entity 수정 
  - [x] 판매중, 품절, 숨김 Status 추가 
  - [x] 최대 인원 == 신청 인원 일시 자동으로 품절로 상태 변경 (이부분은 update나 상태가 바뀔때 따로 처리해줘야 됨)
- [x] 옵션 수정 기능 구현 #79 참고
- [x] 카테고리 수정 기능 구현 (상품 내에서 카테고리를 다른 카테고리로 수정 하는 로직 따라서 모든 카테고리 리스트를 불러오는 api 필요) (기존 모든 카테고리 삭제후 모든 카테고리 리스트에서 체크박스로 넘어온 카테고리들을 새로 넣는 형식)

## References
