### ISSUE TITLE
feat: 검색 기능 구현, 상품 주문 및 주문 내역 조회 기능 수정

### ISSUE THREAD

**Issue by JeYeongR** [KDT3-Final-6/final-project-BE#29]
## Description

- 검색 기능 구현
- 상품 주문 기능 수정
   - 옵션 Status를 추가로 상품 주문 기능 로직에서 Status에 따라 동작해야 한다.
- 주문 내역 조회 기능 수정
   - 주문 Status로 조회 가능하게 만들기

## Tasks(Process)

- [x] 검색 기능 구현
- [x] 상품 주문 기능 수정
   - [x] 옵션 수량 확인하여 품절로 변경시키는 로직 추가
   - [x] 판매중 상품만 주문 가능하게 로직 추가
- [x] 주문 내역 조회 기능 수정
   - [x] 주문 Status에 따라 리스트 바뀌는 로직 추가
