### ISSUE TITLE
feat: 검색 기능 로직 추가

### ISSUE THREAD

**Issue by JeYeongR** [KDT3-Final-6/final-project-BE#36]
## Description

판매 중인 상품만 출력하도록 로직 추가

## Tasks(Process)

- [x] 제목으로 판매 중인 상품만 출력하는 로직 추가
- [x] 카테고리로 판매 중인 상품만 출력하는 로직 추가
- [x] 날짜로 판매 중인 상품만 출력하는 로직 추가
