### ISSUE TITLE
feat: 상품 주문, 주문 내역 조회 기능 및 Order 엔티티 수정

### ISSUE THREAD

**Issue by JeYeongR** [KDT3-Final-6/final-project-BE#39]
## Description

상품 주문 기능 및 Order 엔티티 수정

## Tasks(Process)

- [x] Order 엔티티에 결제수단 필드 추가
- [x] 상품 주문 기능에 결제 수단 받는 로직 추가
- [x] 상품 주문 내역 조회 ResponseDTO에 결제수단 필드 추가
- [x] 상품 주문 내역 조회(관리자용) ResponseDTO에 결제수단 필드 추가
