### ISSUE TITLE
feat: Order 엔티티 수정, 관리자가 결제 승인 기능 구현

### ISSUE THREAD

**Issue by JeYeongR** [KDT3-Final-6/final-project-BE#41]
## Description

Status 필드를 추가 (결제대기 / 결제완료 / 주문취소)

## Tasks(Process)

- [x] isCanceled 필드 삭제
- [x] enum으로 Status 필드 추가
- [x] 관리자가 결제 승인하는 기능 구현
