### ISSUE TITLE
feat: member엔티티 수정, 요청값 변경

### ISSUE THREAD

**Issue by lala9663** [KDT3-Final-6/final-project-BE#49]
## Description

필요한 기능 추가

## Tasks(Process)

- [x] gender, smsAgree, emailAgree 추가하기
- [x] 휴대폰 비밀번호 - 빼기
- [x] 회원 정보 요청 값 변경
- [x] 기본 이미지를 기본값으로 추가하기

## References

- [link text] (link address)
