### ISSUE TITLE
refactor: 검색 기능에 바뀐 카테고리 적용 및 로직 수정

### ISSUE THREAD

**Issue by JeYeongR** [KDT3-Final-6/final-project-BE#58]
## Description

바뀐 카테고리를 검색 기능에 적용합니다.

## Tasks(Process)

- [x] 검색 기능에 바뀐 카테고리 적용
- [x] 검색 기능 로직 수정
- [x] 검색 ResponseDTO 생성
