### ISSUE TITLE
feat: 상품에 위시리스트 수 추가 및 DTO에 위시리스트 표시 추가

### ISSUE THREAD

**Issue by JeYeongR** [KDT3-Final-6/final-project-BE#66]
## Description

위시리스트 기능 구현으로 
상품에 위시리스트 수 필드 추가,
리스트 목록 조회 기능들 DTO에 위시리스트 표시 추가

## Tasks(Process)

- [x] 상품에 위시리스트 수 필드 추가
- [x] 위시리스트 로직 수정
- [x] 검색바 검색 목록 ResponseDTO 수정
- [x] 카테고리 검색 로직 수정
- [x] 카테고리 검색 목록 조회 ResponseDTO 수정
- [ ] 상품 목록 ResponseDTO 수정
