### ISSUE TITLE
refactor: 기간옵션 수정 로직 변경

### ISSUE THREAD

**Issue by zoomin3022** [KDT3-Final-6/final-project-BE#79]
## Description
PeriodOption의 경우 수정을 불가능하게 막고 (이미 여행을 예약하였는데 무통보로 바꾸는것도 생각해보면 이상해서)
기존의 판매중, 품절, 숨김에서 관리자는 숨김을 볼 수 있었는데 
숨김 기능을 없애고 관리자에서도 숨김 처리된 옵션을 볼 수 없는 삭제기능으로서 쓰고자 한다.

## Tasks(Process)

- [x] ProductDetailByMemberDTO 를 제거하고 이 기능을 ProductDetailGetResponseDTO에 적용
- [x] ProductService내의 displayProductDetailByMember 삭제
- [x] ProductController에서 displayProductDetailByMember 대신 displayProductDetail 사용
